# Generated by Django 5.1.2 on 2024-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('parent_company', models.CharField(choices=[('TCS', 'TCS'), ('INFOSYS', 'INFOSYS'), ('TECH-MAHENDRA', 'TECH-MAHENDRA')], max_length=50)),
            ],
        ),
    ]
